config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :users
  # resources :trucks
  root :to => "welcome#index"
  resources :trucks

  get 'welcome/index'
  get 'sessions/new'
  get 'register' => 'trucks#new', :as => :register
  get 'companies/create'
  get 'users/create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/trucks/:id' => 'trucks#reserve'
end

app/models/truck.rb
class Truck < ApplicationRecord
    belongs_to :company

    validates :name, presence: true
    validates :truck_type, :presence => true
    validates :year,:presence => true
    validates :capacity, :presence => true

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: %i[ show edit update reserve destroy ]

  # GET /trucks or /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/1 or /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks or /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: "Truck was successfully created." }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1 or /trucks/1.json
  def update
    logger.debug params[:id] + "this is the id"
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: "Truck was successfully updated." }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1 or /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: "Truck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reserve
    if @truck.reserved
      message = "Reservation removed"
    else
      message = "Truck was successfully reserved"
    end
    @truck.update_attribute(:reserved, !@truck.reserved)
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: message }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truck_params
      params.require(:truck).permit(:name, :truck_type, :year, :company_id, :capacity, :reserved)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= bootstrap_form_with(model: truck, inline_errors: true) do |form| %>

  <div class="field form-group mb-3">
    <%= form.text_field :name %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :truck_type %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :year %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :capacity %>
  </div>

  <div class="field form-group mb-3">
    <%= form.hidden_field :company_id, value: session[:company_id] %>
  </div>

  <div class="field form-group mb-3">
    <%= form.check_box :reserved %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1 class="pt-4 pb-4" >Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck, class: "btn btn-secondary text-white" %> |
<%= link_to 'Back', trucks_path, class: "btn btn-light" %>

app/views/trucks/index.html.erb
<h1 class="pt-4 pb-4" >Trucks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Truck type</th>
      <th>Year</th>
      <th>Capacity</th>
      <th>Reservation Status</th>
      <% if session[:admin] %>
        <th class="text-center">Show</th>
        <th class="text-center">Edit</th>
        <th class="text-center">Delete</th>
      <% else %>
        <th class="text-center"></th>
      <% end %> 
      
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <% if truck.company_id == session[:company_id] %>
        <tr class=" align-middle">
          <td><%= truck.company_id %></td>
          <td><%= truck.truck_type %></td>
          <td><%= truck.year %></td>
          <td><%= truck.capacity %></td>
          <td>
            <% if truck.reserved %>
              <% reservation_text = "Delete Reservation" %>
              <%= fa_icon "lock 2x", text: "Reserved", class: "text-danger align-middle" %>
            <% else %>
              <% reservation_text = "Make Reservation" %>
              <%= fa_icon "unlock 2x", text: "Available", class: "text-success  align-middle" %>
            <% end %>
            </td>
          <% if session[:admin] %>
            <td class="text-center"><%= link_to truck, class: "text-white btn btn-success" do fa_icon "eye" end %></td>
            <td class="text-center"><%= link_to edit_truck_path(truck), class: "text-white btn btn-primary" do  fa_icon "edit"  end %></td>
            <td class="text-center"><%= link_to truck, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white btn btn-danger" do fa_icon "trash" end %></td>
          <% else %>
            <td class="text-center"><%= link_to truck, method: :post, class: "text-white btn btn-primary" do fa_icon "", text: reservation_text  end %></td>
          <% end %> 
        </tr>   
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path, class: "btn btn-secondary text-white" %>

app/views/trucks/new.html.erb
<h1 class="pt-4 pb-4" >New Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', trucks_path, class: "btn btn-light" %>

app/views/trucks/show.html.erb
<table class="table table-striped mx-auto w-auto">

<tr>
<td>Name</td>
<td><%= @truck.name %></td>
</tr>

<tr>
<td>Truck type</td>
<td><%= @truck.truck_type %></td>
</tr>

<tr>
<td>Year</td>
<td><%= @truck.year %></td>
</tr>

<tr>
<td>Capacity</td>
<td><%= @truck.capacity %></td>
</tr>

<tr>
<td>Reserved</td>
<td><%= @truck.reserved %></td>
</tr>

</table>

<%= link_to 'Edit', edit_truck_path(@truck), class: "btn btn-secondary text-white" %> |
<%= link_to 'Back', trucks_path, class: "btn btn-light" %>