config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :users
  # resources :trucks
  root :to => "welcome#index"
  resources :trucks

  get 'welcome/index'
  get 'sessions/new'
  get 'register' => 'trucks#new', :as => :register
  get 'companies/create'
  get 'users/create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/trucks/:id' => 'trucks#reserve'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Truckers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_pack_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container-fluid">
        <div class="navbar-header">
          <img class="nav-truck" src="<%= image_path('truck_grey.png') %>" width="37" height="37"/>
        </div>
        <ul class="navbar-nav d-flex align-items-center">
          <li class="nav-item">
            <%= link_to 'Companies', companies_path, method: :get, class: "nav-link"  %>
          </li>
          <% if session[:user_id] %>
            <% if session[:admin] %>
              <li class="nav-item">
                <%= link_to 'Users', users_path, method: :get, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Trucks', trucks_path, method: :get, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :post, class: "nav-link btn btn-danger text-white" %>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_path, method: :get, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to 'Login', login_path, method: :get, class: "nav-link btn btn-primary text-white" %>
              </li>
            <% end %>

          </ul>
      </div>
    </nav>

    <div class="container">
      <div class="row-fluid">
        <div class="span8">
        <% if flash.notice %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= flash.notice %>
          </div>
        <% end %>
        <% if flash.alert %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= flash.alert %>
          </div>
        <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>